class Attribute
{
	size;
	prog;
	loc;
	value;
	gl;
	buff;
	constructor(attributeSize,shaderProgram,location,attributeValue,glCore)
	{
		this.size=attributeSize;
		this.prog=shaderProgram;
		this.loc=glCore.getAttribLocation(shaderProgram,location);
		this.value=attributeValue;
		this.gl=glCore;
		this.buff=this.gl.createBuffer();
		this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.buff);
		this.gl.bufferData(this.gl.ARRAY_BUFFER,this.value,this.gl.STATIC_DRAW);
	}
	clear()
	{
		if(this.buff)
		{
			this.gl.deleteBuffer(this.buff);
			this.buff=null;
		}
	}
	set(newValue)
	{
		this.clear();
		this.value=newValue;
		this.buff=this.gl.createBuffer();
		this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.buff);
		this.gl.bufferData(this.gl.ARRAY_BUFFER,this.value,this.gl.STATIC_DRAW);
	}
	use()
	{
		this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.buff);
		this.gl.enableVertexAttribArray(this.loc);
		this.gl.vertexAttribPointer(this.loc,this.size,this.gl.FLOAT,false,0,0);
	}
}